version: 1.1.{build}
branches:
  only:
  - master
  - develop
environment:
  fast_finish: true
install:
- cmd: choco install 7zip.commandline
cache:
- C:\ProgramData\chocolatey\lib
- C:\ProgramData\chocolatey\bin
build_script:
- cmd: 7za a -bb0 dummy.miz C:\projects\132nd-virtual-wing-training-mission-tblisi\*
test: off
artifacts:
- path: '*.miz'
  name: TRMT
deploy:
- provider: GitHub
  auth_token:
    secure: 9ksb7+zKJ8riuvzZBaSrD84Mngnd+bs+WXvzhmXSiTe4GtGw/M8v+9J3vqnGTfPd
  artifact: '*.miz'
  draft: true
  on:
    branch: develop